<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace MyOwl\MyOwl\Models\Operations;

use \MyOwl\MyOwl\Utils\SpeakeasyMetadata;
class RegisterRequestBody
{
	#[SpeakeasyMetadata('form:name=email')]
    public ?string $email = null;
    
	#[SpeakeasyMetadata('form:name=lastName')]
    public ?string $lastName = null;
    
    /**
     * First Name
     * 
     * @var ?string $name
     */
	#[SpeakeasyMetadata('form:name=name')]
    public ?string $name = null;
    
	#[SpeakeasyMetadata('form:name=password')]
    public ?string $password = null;
    
	#[SpeakeasyMetadata('form:name=password_confirmation')]
    public ?string $passwordConfirmation = null;
    
    /**
     * 5=Parent, 6=Student
     * 
     * @var ?int $roleId
     */
	#[SpeakeasyMetadata('form:name=roleId')]
    public ?int $roleId = null;
    
	public function __construct()
	{
		$this->email = null;
		$this->lastName = null;
		$this->name = null;
		$this->password = null;
		$this->passwordConfirmation = null;
		$this->roleId = null;
	}
}
